Discover broken links when building absolute links
gardener/docforge pull request #187
Opened 2021-06-09 11:16 UTC by Kristian-ZH

**What this PR does / why we need it**:
Discover broken links when building absolute links

**Which issue(s) this PR fixes**:
Closes #185 
**Special notes for your reviewer**:
@swilen-iwanow 

**Release note**:

```noteworthy user
None
```

2021-06-09 11:25 UTC, swilen-iwanow requested changes
there are failing tests

2021-06-09 11:25 UTC, swilen-iwanow commented on pkg/reactor/content_processor.go
> +			klog.Warningf("absolute link %s not found: %s\n", absLink, err.Error())
```suggestion
			klog.Warningf("failed to read absolute link %s: %v\n", absLink, err)
```

2021-06-09 14:29 UTC, Kristian-ZH commented
> there are failing tests

should be fine now

2021-06-10 10:14 UTC, swilen-iwanow approved these changes

2021-06-10 10:14 UTC, merged