node selector rework
gardener/docforge pull request #259
Opened 2021-12-23 14:57 UTC by Kostov6

**What this PR does / why we need it**:
Reworks the git node selector

**Release note**:

```improvement developer

```

2022-01-04 12:29 UTC, Kristian-ZH requested changes
Some minor comments

2022-01-04 12:29 UTC, Kristian-ZH commented on pkg/resourcehandlers/git/git_resource_handler.go
> +	/*
It is not a good practice to leave a commented code.
If you do not need this, you can just remove it

2022-01-04 12:29 UTC, Kristian-ZH commented on pkg/resourcehandlers/github/resource_locator_cache.go
> +	//???
Why do you need this comment?

2022-01-04 13:35 UTC, Kostov6 commented
>

2022-01-06 10:06 UTC, Kristian-ZH commented on pkg/resourcehandlers/git/git_resource_handler.go
> +	//var files []string
Can you please remove these two commented lines

2022-01-06 10:06 UTC, Kristian-ZH commented on pkg/resourcehandlers/git/git_resource_handler.go
> +		//files = append(files, relativePath)
same

2022-01-27 08:30 UTC, dimitar-kostadinov approved these changes
/lgtm

2022-01-27 08:31 UTC, merged